<a href="https://colab.research.google.com/github/eric-sun92/pytorch_intro/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [3]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
vector.ndim

1

In [24]:
matrix = torch.tensor([[[7, 8], [9, 10], [11, 12]]])
matrix

tensor([[[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [25]:
matrix.shape

torch.Size([1, 3, 2])

In [13]:
matrix.ndim

2

In [27]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
### create a tensor
some_tensor = torch.rand(3, 4)
some_tensor



tensor([[0.9028, 0.8925, 0.9884, 0.6911],
        [0.1240, 0.3186, 0.7200, 0.2611],
        [0.9002, 0.8477, 0.6081, 0.0263]])

In [30]:
some_tensor.dtype


torch.float32

In [31]:
some_tensor.shape

torch.Size([3, 4])

In [33]:
some_tensor.size()

torch.Size([3, 4])

In [34]:
### tensor operations

[link text](https://)

Tensor operations include: 
addition, subtraction, mult, division, matrix-mult

In [42]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [38]:
torch.min(x)


tensor(0)

In [39]:
x.min()

tensor(0)

In [40]:
x.max(
    
)

tensor(90)

In [44]:
# note- torch.mean requires tensor of dtype -> torch.float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [45]:
x.sum()

tensor(450)

In [46]:
torch.sum(x)

tensor(450)

In [52]:
# positional max and min (argmin/argmax) -> returns index of min/max

In [48]:
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(9)

In [50]:
torch.argmin(x)

tensor(0)

In [51]:
torch.argmax(x)

tensor(9)

In [53]:
# reshaping, stacking, squeezing, unsqueeze


In [84]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
#add an extra dimension

In [85]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
# change view

In [86]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [95]:
# changing z changes x because view shares same memory as original input
z[:, 2] = 3
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [100]:
# stack on top of eachother
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [113]:
y = torch.arange(1, 4)
y

tensor([1, 2, 3])

In [126]:
y_repeat = y.repeat(3, 2, 1)
y_repeat

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])

In [134]:
z = torch.stack([y_repeat, y_repeat, y_repeat], dim=3)
z

tensor([[[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],

         [[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]],


        [[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],

         [[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]],


        [[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],

         [[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]]])

In [113]:
# torch.squeeze() remove all single dimensions

In [135]:
z.squeeze()

tensor([[[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],

         [[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]],


        [[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],

         [[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]],


        [[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]],

         [[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3]]]])

In [161]:
x = torch.zeros(9)
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [170]:
x.squeeze()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [179]:
x_unsqueeze = x.unsqueeze(dim=1)
x_unsqueeze

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [184]:
x.shape

torch.Size([9])

In [193]:
h = x_unsqueeze.unsqueeze(dim=0)
h

tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])

In [189]:
x_unsqueeze.shape

torch.Size([9, 1])

In [194]:
h.shape

torch.Size([1, 9, 1])

In [196]:
a = torch.zeros(1, 1, 9)
a

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [198]:
#permute
x_original = torch.rand(size=(224, 224, 3))
x_original

tensor([[[0.3982, 0.6967, 0.2405],
         [0.9151, 0.2285, 0.0389],
         [0.7042, 0.2637, 0.3380],
         ...,
         [0.1787, 0.5464, 0.6227],
         [0.4873, 0.7973, 0.6663],
         [0.5195, 0.9460, 0.3666]],

        [[0.9196, 0.2811, 0.5630],
         [0.5520, 0.3255, 0.0241],
         [0.1442, 0.2843, 0.5987],
         ...,
         [0.3611, 0.9337, 0.2883],
         [0.8512, 0.9865, 0.2831],
         [0.5462, 0.8103, 0.9572]],

        [[0.8152, 0.2177, 0.8108],
         [0.8292, 0.6206, 0.6463],
         [0.1659, 0.5210, 0.0040],
         ...,
         [0.5080, 0.1447, 0.1356],
         [0.5588, 0.4783, 0.7829],
         [0.2013, 0.2275, 0.9508]],

        ...,

        [[0.2037, 0.4352, 0.5172],
         [0.9016, 0.0889, 0.7648],
         [0.7545, 0.6890, 0.0311],
         ...,
         [0.6070, 0.4892, 0.4991],
         [0.3175, 0.6221, 0.8905],
         [0.8552, 0.8715, 0.6566]],

        [[0.9662, 0.5065, 0.2750],
         [0.5749, 0.5026, 0.3425],
         [0.

In [200]:
x_permuted = x_original.permute(2, 0, 1)
x_permuted

tensor([[[0.3982, 0.9151, 0.7042,  ..., 0.1787, 0.4873, 0.5195],
         [0.9196, 0.5520, 0.1442,  ..., 0.3611, 0.8512, 0.5462],
         [0.8152, 0.8292, 0.1659,  ..., 0.5080, 0.5588, 0.2013],
         ...,
         [0.2037, 0.9016, 0.7545,  ..., 0.6070, 0.3175, 0.8552],
         [0.9662, 0.5749, 0.9505,  ..., 0.7237, 0.0402, 0.3500],
         [0.5450, 0.1395, 0.4660,  ..., 0.2381, 0.9826, 0.9599]],

        [[0.6967, 0.2285, 0.2637,  ..., 0.5464, 0.7973, 0.9460],
         [0.2811, 0.3255, 0.2843,  ..., 0.9337, 0.9865, 0.8103],
         [0.2177, 0.6206, 0.5210,  ..., 0.1447, 0.4783, 0.2275],
         ...,
         [0.4352, 0.0889, 0.6890,  ..., 0.4892, 0.6221, 0.8715],
         [0.5065, 0.5026, 0.9048,  ..., 0.9072, 0.2488, 0.2254],
         [0.8037, 0.5685, 0.8053,  ..., 0.4693, 0.7770, 0.4458]],

        [[0.2405, 0.0389, 0.3380,  ..., 0.6227, 0.6663, 0.3666],
         [0.5630, 0.0241, 0.5987,  ..., 0.2883, 0.2831, 0.9572],
         [0.8108, 0.6463, 0.0040,  ..., 0.1356, 0.7829, 0.

In [201]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [202]:
x_original[0, 0, 0] = 723123
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(723123.), tensor(723123.))

In [203]:
# Indexing 


In [204]:
import torch

In [217]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [218]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [219]:
x[:, 0]

tensor([[1, 2, 3]])

In [220]:
x[0][0]

tensor([1, 2, 3])

In [221]:
x[0, 0]

tensor([1, 2, 3])

In [222]:
x[0, 0, 0]

tensor(1)

In [223]:
x[0, 1, 1]

tensor(5)

In [224]:
x[0, 2, 2]

tensor(9)

In [225]:
x[:, 0]

tensor([[1, 2, 3]])

In [226]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [227]:
x[0, :, 2]

tensor([3, 6, 9])

In [229]:
x[:, 1, 1].item()

5

In [231]:
## Pytorch tensors & NumPy
# torch.from_numpy(ndarray), torch.Tensor.numpy()
import torch
import numpy as np

In [243]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [234]:
array.dtype

dtype('float64')

In [240]:
tensor.dtype

torch.float64

In [244]:
array = array + 1

In [245]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [246]:
tensor + 1

tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [247]:
array

array([2., 3., 4., 5., 6., 7., 8.])

In [248]:
tensor += 1

In [249]:
tensor, array

(tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [252]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [253]:
numpy_tensor.dtype

dtype('float32')

In [256]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [257]:
# Reproducability trying to take random out of random


torch.rand(3, 3)

tensor([[0.4502, 0.3000, 0.3169],
        [0.0200, 0.2135, 0.2593],
        [0.6661, 0.2578, 0.9186]])

In [260]:
# to reduce randomness in nn and pytorch, ** random seed

random1 = torch.rand(3, 4)
random2 = torch.rand(3, 4)
print(random1) 
print(random2)
print(random1 == random2)

tensor([[0.3527, 0.3389, 0.4076, 0.8283],
        [0.0873, 0.1314, 0.0296, 0.3673],
        [0.6776, 0.1113, 0.6834, 0.4232]])
tensor([[0.2162, 0.9335, 0.7113, 0.1157],
        [0.3933, 0.7612, 0.6788, 0.0924],
        [0.3754, 0.8751, 0.2227, 0.5346]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [262]:
# set random seed with manual_seed() -> works for 1 block of code

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random3 = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random4 = torch.rand(3, 4)
print(random3)
print(random4)
print(random3 == random4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [2]:
import torch
torch.cuda.is_available()

True

In [8]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [4]:
#count number of devices
torch.cuda.device_count()

1

In [11]:
# putting tensors (and models) on the GPU to make computations faster

tensor = torch.tensor([1, 2, 3])

#tensor not on gpu
print(tensor, tensor.device)

# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [13]:
tensor_on_cpu = tensor_on_gpu.cpu()
tcn = tensor_on_cpu.numpy()
tcn

array([1, 2, 3])