<a href="https://colab.research.google.com/github/eric-sun92/pytorch_intro/blob/00_fundamentals/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# done

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor
rand = torch.rand(7, 7)
rand

tensor([[0.4571, 0.9546, 0.6422, 0.1534, 0.7705, 0.5472, 0.4276],
        [0.4581, 0.3869, 0.0108, 0.7367, 0.1748, 0.8857, 0.4116],
        [0.8633, 0.5156, 0.7064, 0.8367, 0.2685, 0.7775, 0.7001],
        [0.3253, 0.3189, 0.5795, 0.0533, 0.4497, 0.2166, 0.8655],
        [0.5790, 0.9902, 0.5319, 0.8977, 0.1420, 0.4287, 0.5738],
        [0.5759, 0.3460, 0.5167, 0.9442, 0.6617, 0.7094, 0.1330],
        [0.9180, 0.9550, 0.0457, 0.3281, 0.3479, 0.1122, 0.7319]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
rand2 = torch.rand(1, 7)
rand2.transpose_(0, 1)
# Perform matrix multiplication 
mm = torch.matmul(rand, rand2)
mm

tensor([[0.9595],
        [0.7695],
        [1.0054],
        [0.6989],
        [0.7119],
        [0.9903],
        [0.6856]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand01 = torch.rand(7, 7)
rand02 = torch.rand(1, 7)

rand02.transpose_(0, 1)
rand01, rand02

# Matrix multiply tensors
mm0 = torch.matmul(rand01, rand02)
mm0

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f'Device: {device}')

# Create two random tensors on GPU
rand1_gpu = torch.rand(2, 3).to(device)
rand2_gpu = torch.rand(2, 3).to(device)
rand1_gpu, rand2_gpu


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
rand2_gpu.transpose_(0, 1)
mm_gpu = torch.matmul(rand1_gpu, rand2_gpu)
mm_gpu, mm_gpu.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
print(mm_gpu.max())

# Find min
print(mm_gpu.min())


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
print(mm_gpu.argmax())

# Find arg min
print(mm_gpu.argmin())

mm_gpu

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand = torch.rand(1, 1, 1, 10)
print(rand, rand.shape)

# Remove single dimensions
squeezed = rand.squeeze()
print(squeezed, squeezed.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
